config/routes.rb
Rails.application.routes.draw do

  resources :links, only: [:index, :new, :show, :create]
  
  get '/:id' => 'redirect#show'
  
  root 'links#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  before_create :set_count_to_zero
  before_create :generate_slug
  
  private
  
    def set_count_to_zero
      self.count = 0
    end
    
    def generate_slug
      self.slug = Base64.urlsafe_encode64(self.original).split('').shuffle.join.gsub("=","").slice(0,6)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end


  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Copy your shortened URL below!' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:original)
    end
end

app/controllers/redirect_controller.rb
class RedirectController < ApplicationController
  def show
    #get slug from params
    slug = params[:id]
    #find the orginal url
    link = Link.find_by(slug: slug)
    if link
      #increment count
      link.count = link.count + 1
      link.save
      #redirect user
      redirect_to link.original
    else
      redirect_to root_url, notice: 'No link found'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
  
  def slug_url(slug)
    "https://shortner-2-johnsonch.c9users.io/#{slug}"
  end
  
end

app/helpers/redirect_helper.rb
module RedirectHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for(link) do |f| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :original, "URL to shorten" %>
    <%= f.text_area :original %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th>Original</th>
      <th>Count</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.original %></td>
        <td><%= link.count %></td>
        <td><%= link_to slug_url(link.slug), slug_url(link.slug) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= slug_url(@link.slug) %>
</h2>

app/views/redirect/show.html.erb
<h1>Redirect#show</h1>
<p>Find me in app/views/redirect/show.html.erb</p>